services:
  db:
    image: postgres:15
    container_name: rider-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: rider_db
    ports:
      - "5432:5432"